### ISSUE TITLE
Trolleybus and sometimes tram wires are missing on crossings with lanes altered using TM:PE

### ISSUE THREAD

**Issue by zubozrout** [CitiesSkylinesMods/HideUnconnectedTracks#1]
Hi,
I was for some reason unable to quickly find this repo initially which is why I first [reported this issue on Steam](https://steamcommunity.com/workshop/filedetails/discussion/2019097300/3417685728354618590).

So I am sorry for the double spam. However I feel like it is better to keep track of this here.

To sum things up it seems starting with V1.4.1 the catenary is missing on all trolleybus and some tram intersections when one starts altering the intersection lanes with TM:PE.

Thank you.

**Comment by kianzarrin** [comment]
do you use hide unconnected tracks?

**Comment by kianzarrin** [comment]
give us logs

**Comment by zubozrout** [comment]
Hello @kianzarrin.
Of course, this mod exactly: https://steamcommunity.com/sharedfiles/filedetails/?id=2019097300

As for the logs, I am happy to do so. But a few questions:

- Is there are any specific log file? I only could find some mess inside the main Player.log, so I a attaching that one at least.
- Can't you reproduce? (because if you can't that is very interesting indeed, especially considering there are more people facing the same issue)

The log I am attaching is with the V1.4.1 downloaded from this repo, but it behaves the same with the latest workshop item as well (and I presume these are 1:1 the same anyway)

[Player.log](https://github.com/CitiesSkylinesMods/HideUnconnectedTracks/files/9759894/Player.log)

And a little side note. I also manually enabled V1.3.1 downloaded from this repo - hoping to give it a try. But sadly I am getting this on game load. Possibly incompatible with the latest TM:PE?:
```
Could not load type
'TrafficManager.Manager.Impl.LaneConnectionManag
from assembly 'HideUnconnectedTracks'.
System.TypeLoadException

Details:
No details
```

Thank you

**Comment by kianzarrin** [comment]
> And a little side note. I also manually enabled V1.3.1 downloaded from this repo - hoping to give it a try. But sadly I am getting this on game load. Possibly incompatible with the latest TM:PE?:

the API has changed yes.

**Comment by kianzarrin** [comment]
I see I can reproduce.

**Comment by kianzarrin** [comment]
I will fix.

**Comment by kianzarrin** [comment]
Thanks for reporting this issue. 
I fixed it:
![image](https://user-images.githubusercontent.com/26344691/195273945-b763309d-6173-434c-a667-f968f0e25b4c.png)

**Comment by zubozrout** [comment]
Thank you so much @kianzarrin. This is awesome :tada: 
I'll give it a try once a new build is available but if it works for you now I'd say feel free to close the ticket :wink:

**Comment by zubozrout** [comment]
Sorry to bother you @kianzarrin, but there are sadly remaining issues with this.

1. For classic intersection like on your screenshot the wires swing as if they were tram tracks for some reason. Interesting it is not the case on your screenshot but could be because of the paused game perhaps. Sort of visible on the first screenshot attached below.
2. Most crossings however do not work as intended and are still missing wires, as per my second screenshot.

![swing](https://user-images.githubusercontent.com/3088349/195694374-8f0dd454-64d5-455a-bfd4-3257380e37f8.png)
![broken](https://user-images.githubusercontent.com/3088349/195694385-e4e32198-b17b-4b3c-9759-a6dc198c0226.png)

Thank you very much and sorry for this pain.

**Comment by kianzarrin** [comment]
fixed the wind issue.

**Comment by kianzarrin** [comment]
there is a fundamental bug . was this always like this?
![image](https://user-images.githubusercontent.com/26344691/195712480-49c91f99-bf53-4969-a1c6-409acaadbdad.png)

**Comment by zubozrout** [comment]
Thank you @kianzarrin. And interesting. But no, it used to work. With trains though there was/is a mechanism in which if you made the angle too large it would be disconnected like this but on your image this still seems within the limit :thinking:

But I can't see a difference in between having the mod enabled and not in these cases:

![Screenshot 14](https://user-images.githubusercontent.com/3088349/195811615-f4c4d1c5-ce9e-46c5-b584-0ad4d9671c42.png)
![Screenshot 13](https://user-images.githubusercontent.com/3088349/195811626-fabf8d87-b06a-4a31-87bf-4005d7177c84.png)

But, it breaks the minute I start applying lanes. That only broke with V1.4.1+ and makes sense why people started reporting trams are also broken (though in my case only sometimes).

![Screenshot 12](https://user-images.githubusercontent.com/3088349/195813624-0499a7a6-5ad7-42d5-9fe3-54cb173e22a1.png)

Very weird :disappointed:

**Comment by kianzarrin** [comment]
1.4.1 was a long time ago. I can't believe it. I remember testing everything. it can't be.

**Comment by zubozrout** [comment]
Not sure if it was related or TM:PE related or even something else. But first report I can find is in the mod's comments (on Steam) by Michu (16 June 2022, 19.51:36 CEST) and I've noticed roughly the same time.

That is shortly after the "V1.4.1 TMPE API update - faster" release but I am not sure if it worked for some time in between the release and perhaps other game/mod update if there was any as I wasn't playing Cities: Skylines in between afaik.

**Comment by kianzarrin** [comment]
I am sure its a stupid oversight. I narrowed it down to this minimal test case:
![image](https://user-images.githubusercontent.com/26344691/195862519-0234db29-b9f5-4da9-a95d-05fe2c0c4442.png)
it should say render the original node but it gets confused.

**Comment by kianzarrin** [comment]
ok fixed it. will push release to github now.

**Comment by kianzarrin** [comment]
BTW for testing you can connect lane to itself to make sure it goes nowhere.

**Comment by zubozrout** [comment]
This is perfect, thank you @kianzarrin. It seems to work as expected - hopefully every intersection that worked for me before works now.

One thing that might have been the case before or not, not sure is that resetting lanes for trains doesn't seem to actually reset wires - they stay detached until I connect them again. But it works for roads (trolleybuses). Could also be TM:PE issue itself - probably more likely considering what happens there.

![Screenshot 12](https://user-images.githubusercontent.com/3088349/195883000-fc66e7f0-8b44-4514-b941-d5afe9a2536e.png)

**Comment by kianzarrin** [comment]
>  resetting lanes for trains doesn't seem to actually reset wires

not sure what that image is about. is it only the wires or the tracks too? maybe the angle is to acute?

**Comment by kianzarrin** [comment]
you may know this already but if you use [Adaptive networks](https://steamcommunity.com/sharedfiles/filedetails/?id=2669938594) compatible networks you don't have to put up with any of limitations of hide unconnected tracks mod.

**Comment by zubozrout** [comment]
Sorry for the delay. So, to answer to "not sure what that image is about. is it only the wires or the tracks too? maybe the angle is to acute?"

- If build this kind of intersection wires and track are in place.
- If I connect the lanes it stays, that's ok.
- If I disconnect the lanes the track & catenary stays disconnected.

It happens with any angle but I've only noticed this is the case for train tracks. But as mentioned it could have also been the case before June this year, I never noticed. Could be a TM:PE bug and more likely it is as this mod is only related to rendering things based on lanes and shouldn't change any lanes logic I presume.

And thank you, I didn't know Adaptive networks.

**Comment by kianzarrin** [comment]
> I didn't know Adaptive networks.

it only works with AN compatible networks. like some of the later rev0 networks. there is a list in mod page but I don't think its complete.

**Comment by kianzarrin** [comment]
> If build this kind of intersection wires and track are in place.
    If I connect the lanes it stays, that's ok.
    If I disconnect the lanes the track & catenary stays disconnected.

I can't reproduce. do you have steam? what version of TMPE and Hide Unconnected Tracks are you using?

**Comment by kianzarrin** [comment]
![image](https://user-images.githubusercontent.com/26344691/196002100-d9fd86da-9f96-4c53-9728-5b7fc8229f59.png)

**Comment by kianzarrin** [comment]
![image](https://user-images.githubusercontent.com/26344691/196002126-664f32b6-486f-47fd-a787-36c89d83d0f8.png)
I think we have a TMPE bug.

**Comment by kianzarrin** [comment]
~~damn can't reproduce it anymore.
@zubozrout can you still reproduce it? can you please use Move IT mode. select all the segments and export it and give it to me?
also please tell me TMPE version you are using. it should be in the log. has steam downloaded latest TMPE?~~

**Comment by kianzarrin** [comment]
@zubozrout I fixed the TMPE issue https://github.com/CitiesSkylinesMods/TMPE/pull/1679
you can download the TMPE.zip file there to test.

**Comment by zubozrout** [comment]
Sorry for the delay @kianzarrin, I was away and then had a very busy week. This is perfect, thank you so much! :tada: For this as well as for the TMPE fix.
